### ISSUE TITLE
Little confused

### ISSUE THREAD

**Issue by ugintl** [Roskus/hammercrm#2]
The description says laravel 5, whereas, the About section says Laravel 7.2.

Also when I go to Projects Tab on this repo, I see some TO DOs and In progress. Can you please list down the features, currently working, In progress and planned for future, in the read me/description? So that anyone can easily see.

**Comment by gnovaro** [comment]
Hi thanks four your interest in the project is WIP, we are working to upgrade to new laravel version too. And the project process is under beta process.

**Comment by gnovaro** [comment]
README file was updated in last commit
