### ISSUE TITLE
Group the commands

### ISSUE THREAD

**Issue by elguitarraverde** [Roskus/hammercrm#44]
You can group commands by including the name of the app in the command name.

![image](https://user-images.githubusercontent.com/2836337/201480376-07fb7702-4844-451b-bfc5-24792edb5d41.png)

**Comment by gnovaro** [comment]
Interesting i found a possible solution an is easy https://stackoverflow.com/questions/52576074/is-it-possible-or-recommended-to-group-laravel-commands-into-nested-groups

We can try it

**Comment by gnovaro** [comment]
![imagen](https://user-images.githubusercontent.com/270990/201489932-d588c1b9-44a1-4326-ab1e-13ba2527552a.png)
