### ISSUE TITLE
Sidebar submenu

### ISSUE THREAD

**Issue by gnovaro** [Roskus/hammercrm#45]
Email 
  -> Campaign
  -> Template
  -> Email

**Comment by gnovaro** [comment]
IDEM Top bar
![image](https://user-images.githubusercontent.com/270990/202052459-67517372-eee6-46d8-8f4f-dea31d14ecef.png)

**Comment by elguitarraverde** [comment]
We have solved this issue with this commit.

https://github.com/Roskus/hammercrm/commit/bad6767e50d11b7108b480a0f5bc9dec8bb2c6de
