### ISSUE TITLE
User profile timezone

### ISSUE THREAD

**Issue by gnovaro** [Roskus/hammercrm#58]
- Add timezone select
- Migration for alter user table, make the field nullable
- Save user profile
- Calendar events should be saved with timezone

**Comment by elguitarraverde** [comment]
Do you need to add the time zone question in the Create User command similar to the one below?

$lang = $this->ask('What is the lang of the user? (en/es)');

**Comment by elguitarraverde** [comment]
- [ ] Add timezone select
- [ ] Migration for alter user table, make the field nullable
- [ ] Save user profile
- [ ] Calendar events should be saved with timezone

https://github.com/Roskus/hammercrm/commit/2ffd10ff36bdd471270a2ae412238dba87886ed7

Now all event dates are saved in the UTC timezone, calculated from the user's timezone.
